name: Build & Deploy

on:
    push:
        branches: [main]

jobs:
    build-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout node
              uses: actions/checkout@v3

            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.22"

            - name: Build Go app
              run: |
                  go build -o ./build/app ./cmd/api

            - name: Upload binary to VPS
              uses: appleboy/scp-action@v0.1.4
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.VPS_SECRET }}
                  port: 22
                  source: "build/app"
                  target: "/home/supritech"

            - name: Move binary to /var/www with sudo
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.VPS_SECRET }}
                  port: 22
                  script: |
                      mv /home/supritech/build/app /var/www/api-alih-media/app
